# Generated by Django 5.1 on 2024-08-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdTemporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_id', models.CharField(max_length=20, unique=True, verbose_name='numero_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
            options={
                'verbose_name': 'ID temporal',
                'verbose_name_plural': 'ID temporales',
                'db_table': 'temporal',
            },
        ),
    ]
